# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(481, 587)
        font = QtGui.QFont()
        font.setPointSize(24)
        Dialog.setFont(font)
        Dialog.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.name = QtWidgets.QLabel(parent=Dialog)
        self.name.setGeometry(QtCore.QRect(30, 20, 241, 71))
        self.name.setObjectName("name")
        self.surname = QtWidgets.QLabel(parent=Dialog)
        self.surname.setGeometry(QtCore.QRect(30, 80, 231, 91))
        self.surname.setObjectName("surname")
        self.textname = QtWidgets.QTextEdit(parent=Dialog)
        self.textname.setGeometry(QtCore.QRect(210, 40, 241, 41))
        self.textname.setObjectName("textname")
        self.textsurname = QtWidgets.QTextEdit(parent=Dialog)
        self.textsurname.setGeometry(QtCore.QRect(210, 110, 241, 41))
        self.textsurname.setObjectName("textsurname")
        self.wizyta = QtWidgets.QCheckBox(parent=Dialog)
        self.wizyta.setGeometry(QtCore.QRect(30, 380, 311, 51))
        self.wizyta.setChecked(True)
        self.wizyta.setObjectName("wizyta")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 450, 241, 101))
        self.pushButton.setObjectName("pushButton")
        self.resoult = QtWidgets.QLabel(parent=Dialog)
        self.resoult.setGeometry(QtCore.QRect(300, 210, 161, 361))
        self.resoult.setStyleSheet("color: rgb(255, 255, 255);")
        self.resoult.setObjectName("resoult")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(40, 190, 229, 172))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.internista = QtWidgets.QRadioButton(parent=self.widget)
        self.internista.setObjectName("internista")
        self.verticalLayout.addWidget(self.internista)
        self.pediatra = QtWidgets.QRadioButton(parent=self.widget)
        self.pediatra.setObjectName("pediatra")
        self.verticalLayout.addWidget(self.pediatra)
        self.dermatolog = QtWidgets.QRadioButton(parent=self.widget)
        self.dermatolog.setObjectName("dermatolog")
        self.verticalLayout.addWidget(self.dermatolog)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name.setText(_translate("Dialog", "Imie"))
        self.surname.setText(_translate("Dialog", "Nazwisko"))
        self.wizyta.setText(_translate("Dialog", "wizyta prywatna"))
        self.pushButton.setText(_translate("Dialog", "zarezerwuj"))
        self.resoult.setText(_translate("Dialog", "a"))
        self.internista.setText(_translate("Dialog", "internista"))
        self.pediatra.setText(_translate("Dialog", "pediatra"))
        self.dermatolog.setText(_translate("Dialog", "dermatolog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
